use_frameworks!

platform :ios, '10.0'

target 'LockheedBLE_Example' do
  pod 'LockheedBLE', :path => '../'

  target 'LockheedBLE_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
